import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, type UseFormRegisterReturn } from "react-hook-form";
import { Bell, CalendarCheck, Heart, ImagePlus, Plus, Search, Sparkles, Trash2, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AnnouncementCard, BookingCard, PetCard, ServiceCard, VetCard } from "@/components/petlink/Cards";
import { EmptyState } from "@/components/petlink/EmptyState";
import { SkeletonGrid } from "@/components/petlink/SkeletonGrid";
import { authApi, marketplaceApi, petsApi } from "@/lib/petlink-api";
import { normalizeBookingStatus, type Booking, type BookingStatus, type PetSex } from "@/lib/petlink-data";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

const petSchema = z.object({ name: z.string().min(2, "Nombre requerido"), species: z.string().min(2, "Especie requerida"), breed: z.string().min(2, "Raza requerida"), age: z.coerce.number().int().min(0).max(100), weight: z.coerce.number().positive("Peso requerido"), sex: z.enum(["MALE", "FEMALE"]), description: z.string().max(400).optional(), isSterilized: z.boolean().optional(), isVaccinated: z.boolean().optional() });
const profileSchema = z.object({ fullName: z.string().min(2, "Ingresa tu nombre").max(120), phone: z.string().max(30).optional(), city: z.string().max(80).optional() });
const serviceSchema = z.object({ type: z.string().min(2, "Tipo requerido"), title: z.string().min(3, "Título requerido").max(160), description: z.string().min(10, "Describe el servicio").max(2000), price: z.coerce.number().positive("Precio requerido"), location: z.string().min(2, "Ubicación requerida"), availabilityNotes: z.string().optional(), isActive: z.boolean().optional() });
const bookingSchema = z.object({ petId: z.string().min(1, "Selecciona una mascota"), bookingDate: z.string().min(1, "Selecciona una fecha"), durationHours: z.coerce.number().int().positive().optional(), notes: z.string().optional() });

type PetValues = z.infer<typeof petSchema>;
type ProfileValues = z.infer<typeof profileSchema>;
type ServiceValues = z.infer<typeof serviceSchema>;
type BookingValues = z.infer<typeof bookingSchema>;

function useApiError() {
  const { signOut } = useAuth();
  return async (error: unknown) => {
    const status = typeof error === "object" && error && "status" in error ? Number((error as { status: unknown }).status) : 0;
    if (status === 401) {
      toast.error("Tu sesión expiró. Vuelve a ingresar.");
      await signOut();
      return;
    }
    toast.error(error instanceof Error ? error.message : "No se pudo completar la operación");
  };
}

export function DashboardPage() {
  const { role } = useAuth();
  const bookings = useQuery({ queryKey: ["bookings", role], queryFn: () => marketplaceApi.bookings.list(role === "PROVIDER" ? "provider" : "owner") });
  const pets = useQuery({ queryKey: ["pets"], queryFn: petsApi.list, enabled: role === "OWNER" });
  return <Page title={role === "OWNER" ? "Hola, tu familia peluda te espera" : "Panel de proveedor"} action={role === "OWNER" ? <Button asChild variant="hero"><Link to="/services"><Search />Buscar servicio</Link></Button> : <Button asChild variant="hero"><Link to="/my-services/new"><Plus />Nuevo servicio</Link></Button>}><div className="grid gap-4 md:grid-cols-3"><Stat icon={<Heart />} label={role === "OWNER" ? "Mascotas" : "Perfil proveedor"} value={role === "OWNER" ? String(pets.data?.length ?? "—") : "Activo"} /><Stat icon={<CalendarCheck />} label="Reservas" value={String(bookings.data?.length ?? "—")} /><Stat icon={<WalletCards />} label={role === "OWNER" ? "Servicios" : "Estado"} value={role === "OWNER" ? "Real" : "Online"} /></div><section className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><h2 className="mb-4 text-2xl font-black">Próximas reservas</h2>{bookings.isLoading ? <SkeletonGrid /> : bookings.data?.length ? <div className="space-y-4">{bookings.data.slice(0, 2).map((booking) => <BookingCard key={booking.id} booking={booking} />)}</div> : <EmptyState title="Sin reservas" description="Cuando tengas reservas activas, aparecerán aquí." />}</div><div><h2 className="mb-4 text-2xl font-black">Recomendaciones</h2><div className="rounded-card border bg-card p-6 shadow-soft"><Sparkles className="h-8 w-8 text-primary" /><h3 className="mt-4 text-xl font-extrabold">Servicios conectados</h3><p className="mt-2 text-muted-foreground">Explora proveedores reales y reserva con tus mascotas registradas.</p><Button asChild className="mt-5" variant="soft"><Link to="/services">Ver servicios</Link></Button></div></div></section></Page>;
}

export function PetsPage() { const { data, isLoading, error } = useQuery({ queryKey: ["pets"], queryFn: petsApi.list }); return <Page title="Mis mascotas" action={<Button asChild variant="hero"><Link to="/pets/new"><Plus />Nueva mascota</Link></Button>}>{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar las mascotas" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data?.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.map((pet) => <Link key={pet.id} to={`/pets/${pet.id}`}><PetCard pet={pet} /></Link>)}</div> : <EmptyState title="Aún no tienes mascotas" description="Agrega tu primera mascota para reservar servicios personalizados." action="Crear mascota" />}</Page>; }

export function PetFormPage() {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const form = useForm<PetValues>({ resolver: zodResolver(petSchema), defaultValues: { name: "", species: "", breed: "", age: 1, weight: 1, sex: "FEMALE", description: "", isSterilized: false, isVaccinated: true } });
  const [file, setFile] = useState<File | null>(null);
  const mutation = useMutation({ mutationFn: (values: PetValues) => petsApi.create({ name: values.name, species: values.species, breed: values.breed, age: values.age, weight: values.weight, sex: values.sex as PetSex, description: values.description || null, isSterilized: values.isSterilized, isVaccinated: values.isVaccinated }), onSuccess: async (pet) => { let imageUploadFailed = false; if (file) { try { await petsApi.uploadImage(pet.id, file); } catch { imageUploadFailed = true; } } await queryClient.invalidateQueries({ queryKey: ["pets"] }); if (imageUploadFailed) { toast.success("Mascota guardada. La foto no se pudo subir; puedes intentarlo de nuevo más tarde."); } else { toast.success("Mascota guardada correctamente"); } navigate(`/pets/${pet.id}`); }, onError: (error) => { toast.error(error instanceof Error ? error.message : "No se pudo guardar la mascota"); } });
  return <Page title="Nueva mascota"><form className="grid gap-5 rounded-card border bg-card p-6 shadow-soft md:grid-cols-2" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><Input label="Nombre" error={form.formState.errors.name?.message} props={form.register("name")} /><Input label="Especie" error={form.formState.errors.species?.message} props={form.register("species")} /><Input label="Raza" error={form.formState.errors.breed?.message} props={form.register("breed")} /><Input label="Edad" type="number" error={form.formState.errors.age?.message} props={form.register("age")} /><Input label="Peso" type="number" error={form.formState.errors.weight?.message} props={form.register("weight")} /><label className="block text-sm font-bold">Sexo<select className="input-shell mt-2" {...form.register("sex")}><option value="FEMALE">Hembra</option><option value="MALE">Macho</option></select></label><label className="md:col-span-2 block text-sm font-bold">Imagen de mascota<div className="mt-2 flex items-center gap-3 rounded-card border border-dashed p-4"><ImagePlus className="text-primary" /><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(e) => setFile(e.target.files?.[0] ?? null)} aria-label="Subir imagen de mascota" /></div><span className="mt-2 block text-xs font-normal text-muted-foreground">En celular podrás tomar la foto con la cámara o elegirla desde tu galería.</span></label><label className="md:col-span-2 block text-sm font-bold">Descripción<textarea className="input-shell mt-2 min-h-28" {...form.register("description")} /></label><label className="font-bold"><input type="checkbox" className="mr-2" {...form.register("isSterilized")} />Esterilizada</label><label className="font-bold"><input type="checkbox" className="mr-2" {...form.register("isVaccinated")} />Vacunas al día</label><Button className="md:col-span-2" variant="hero" type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Guardando…" : "Guardar mascota"}</Button></form></Page>;
}

export function PetDetailPage() { const { id } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const handleError = useApiError(); const { data: pet, isLoading, error } = useQuery({ queryKey: ["pets", id], queryFn: () => petsApi.get(id ?? ""), enabled: Boolean(id) }); const deleteMutation = useMutation({ mutationFn: (petId: string) => petsApi.remove(petId), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["pets"] }); toast.success("Mascota eliminada correctamente"); navigate("/pets"); }, onError: handleError }); return <Page title={pet?.name ?? "Mascota"} action={<div className="flex gap-3"><Button asChild variant="outline"><Link to="/pets">Volver</Link></Button><Button variant="outline" disabled={deleteMutation.isPending || !id} onClick={() => { if (!id) return; if (!window.confirm("¿Seguro que quieres eliminar esta mascota?")) return; deleteMutation.mutate(id); }}><Trash2 className="h-4 w-4" />{deleteMutation.isPending ? "Eliminando..." : "Eliminar"}</Button></div>}>{isLoading ? <SkeletonGrid /> : error || !pet ? <EmptyState title="Mascota no encontrada" description={error instanceof Error ? error.message : "No pudimos cargar el detalle."} /> : <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><PetCard pet={pet} /><section className="rounded-card border bg-card p-6 shadow-soft"><h2 className="text-2xl font-black">Detalle</h2><div className="mt-5 grid gap-3 text-sm"><p><strong>Peso:</strong> {pet.weight} kg</p><p><strong>Sexo:</strong> {pet.sex === "FEMALE" ? "Hembra" : "Macho"}</p><p><strong>Esterilizada:</strong> {pet.isSterilized ? "Sí" : "No"}</p><p><strong>Vacunas:</strong> {pet.isVaccinated ? "Al día" : "Pendientes"}</p></div></section></div>}</Page>; }

export function ServicesPage() { const [location, setLocation] = useState(""); const [type, setType] = useState(""); const { data = [], isLoading, error } = useQuery({ queryKey: ["services", type, location], queryFn: () => marketplaceApi.services.list({ type, location, isActive: true }) }); return <Page title="Explorar servicios" action={<Button variant="soft"><Search />Filtros</Button>}><div className="mb-5 grid gap-3 md:grid-cols-4"><input className="input-shell md:col-span-2" placeholder="Ciudad" value={location} onChange={(e) => setLocation(e.target.value)} aria-label="Buscar servicios por ciudad" /><input className="input-shell" placeholder="Tipo" value={type} onChange={(e) => setType(e.target.value)} aria-label="Categoría" /><select className="input-shell" aria-label="Orden"><option>Disponibles</option></select></div>{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar los servicios" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data.length ? <div className="grid gap-5 md:grid-cols-3">{data.map((service) => <Link key={service.id} to={`/services/${service.id}`}><ServiceCard service={service} /></Link>)}</div> : <EmptyState title="Sin servicios" description="No hay servicios disponibles con esos filtros." />}</Page>; }

export function ServiceDetailPage() {
  const { id } = useParams();
  const queryClient = useQueryClient();
  const handleError = useApiError();
  const { data: service, isLoading, error } = useQuery({ queryKey: ["services", id], queryFn: () => marketplaceApi.services.get(id ?? ""), enabled: Boolean(id) });
  const pets = useQuery({ queryKey: ["pets"], queryFn: petsApi.list });
  const form = useForm<BookingValues>({ resolver: zodResolver(bookingSchema), defaultValues: { petId: "", bookingDate: "", durationHours: 1, notes: "" } });
  const mutation = useMutation({ mutationFn: (values: BookingValues) => marketplaceApi.bookings.create({ petId: values.petId, serviceId: id ?? "", bookingDate: new Date(values.bookingDate).toISOString(), durationHours: values.durationHours, notes: values.notes || null }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["bookings"] }); toast.success("Reserva creada correctamente"); }, onError: handleError });
  return <Page title={service?.title ?? "Servicio"} action={<Button asChild variant="outline"><Link to="/services">Volver</Link></Button>}>{isLoading ? <SkeletonGrid /> : error || !service ? <EmptyState title="Servicio no encontrado" description={error instanceof Error ? error.message : "No pudimos cargar el servicio."} /> : <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><ServiceCard service={service} /><aside className="rounded-card border bg-card p-6 shadow-soft"><h2 className="text-2xl font-black">Reserva rápida</h2><form onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><label className="mt-4 block text-sm font-bold">Fecha<input type="datetime-local" className="input-shell mt-2" {...form.register("bookingDate")} /></label><label className="mt-4 block text-sm font-bold">Mascota<select className="input-shell mt-2" {...form.register("petId")}><option value="">Selecciona</option>{pets.data?.map((pet) => <option key={pet.id} value={pet.id}>{pet.name}</option>)}</select></label><Input label="Horas" type="number" error={form.formState.errors.durationHours?.message} props={form.register("durationHours")} /><Button className="mt-5 w-full" variant="hero" disabled={mutation.isPending}>{mutation.isPending ? "Reservando…" : "Confirmar reserva"}</Button></form></aside></div>}</Page>;
}

export function BookingsPage({ provider = false }: { provider?: boolean }) { const queryClient = useQueryClient(); const handleError = useApiError(); const { data = [], isLoading, error } = useQuery({ queryKey: ["bookings", provider ? "provider" : "owner"], queryFn: () => marketplaceApi.bookings.list(provider ? "provider" : "owner") }); const mutation = useMutation({ mutationFn: ({ id, status }: { id: string; status: BookingStatus | Booking["status"] }) => marketplaceApi.bookings.updateStatus(id, { status: String(status).toUpperCase() as Uppercase<BookingStatus> }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["bookings"] }); toast.success("Estado actualizado"); }, onError: handleError }); return <Page title={provider ? "Reservas entrantes" : "Mis reservas"}>{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar las reservas" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data.length ? <div className="space-y-4">{data.map((booking) => <BookingCard key={booking.id} booking={booking} onStatus={provider && normalizeBookingStatus(booking.status) === "pending" ? (status) => mutation.mutate({ id: booking.id, status }) : undefined} />)}</div> : <EmptyState title="Sin reservas" description="Cuando reserves un servicio, aparecerá aquí." />}</Page>; }

export function AnnouncementsPage() { const { data = [], isLoading, error } = useQuery({ queryKey: ["announcements"], queryFn: () => marketplaceApi.announcements.list({ isActive: true }) }); return <Page title="Anuncios" action={<Button variant="hero"><Plus />Publicar</Button>}>{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar los anuncios" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data.length ? <div className="grid gap-5 md:grid-cols-2">{data.map((item) => <AnnouncementCard key={item.id} announcement={item} />)}</div> : <EmptyState title="Sin anuncios" description="No hay anuncios activos por ahora." />}</Page>; }
export function VetsPage() { const { data = [], isLoading, error } = useQuery({ queryKey: ["vets"], queryFn: () => marketplaceApi.vets.list({ isActive: true }) }); return <Page title="Directorio de veterinarias">{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar las veterinarias" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{data.map((vet) => <VetCard key={vet.id} vet={vet} />)}</div> : <EmptyState title="Sin veterinarias" description="No hay veterinarias activas registradas." />}</Page>; }
export function ProviderServicesPage() { const { profile } = useAuth(); const { data = [], isLoading, error } = useQuery({ queryKey: ["provider-services", profile?.userId], queryFn: () => marketplaceApi.services.list({ providerId: profile?.userId }), enabled: Boolean(profile?.userId) }); return <Page title="Mis servicios" action={<Button asChild variant="hero"><Link to="/my-services/new"><Plus />Nuevo</Link></Button>}>{isLoading ? <SkeletonGrid /> : error ? <EmptyState title="No se pudieron cargar tus servicios" description={error instanceof Error ? error.message : "Intenta nuevamente."} /> : data.length ? <div className="grid gap-5 md:grid-cols-3">{data.map((service) => <Link key={service.id} to={`/my-services/${service.id}/edit`}><ServiceCard service={service} /></Link>)}</div> : <EmptyState title="Aún no tienes servicios" description="Crea tu primer servicio para recibir reservas." />}</Page>; }
export function ProviderServiceFormPage() { const { id } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const handleError = useApiError(); const editing = Boolean(id); const { data: service } = useQuery({ queryKey: ["services", id], queryFn: () => marketplaceApi.services.get(id ?? ""), enabled: editing }); const form = useForm<ServiceValues>({ resolver: zodResolver(serviceSchema), values: service ? { type: service.type, title: service.title, description: service.description, price: service.price, location: service.location, availabilityNotes: service.availabilityNotes ?? "", isActive: service.isActive } : { type: "", title: "", description: "", price: 1, location: "", availabilityNotes: "", isActive: true } }); const mutation = useMutation({ mutationFn: (values: ServiceValues) => editing ? marketplaceApi.services.update(id ?? "", { type: values.type, title: values.title, description: values.description, price: values.price, location: values.location, availabilityNotes: values.availabilityNotes || null, isActive: values.isActive }) : marketplaceApi.services.create({ type: values.type, title: values.title, description: values.description, price: values.price, location: values.location, availabilityNotes: values.availabilityNotes || null, isActive: values.isActive }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["provider-services"] }); toast.success("Servicio guardado correctamente"); navigate("/my-services"); }, onError: handleError }); return <Page title={editing ? "Editar servicio" : "Nuevo servicio"}><form className="grid gap-5 rounded-card border bg-card p-6 shadow-soft md:grid-cols-2" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><Input label="Tipo" error={form.formState.errors.type?.message} props={form.register("type")} /><Input label="Título" error={form.formState.errors.title?.message} props={form.register("title")} /><Input label="Precio" type="number" error={form.formState.errors.price?.message} props={form.register("price")} /><Input label="Ubicación" error={form.formState.errors.location?.message} props={form.register("location")} /><label className="md:col-span-2 block text-sm font-bold">Descripción<textarea className="input-shell mt-2 min-h-28" {...form.register("description")} /></label><label className="md:col-span-2 block text-sm font-bold">Disponibilidad<textarea className="input-shell mt-2" {...form.register("availabilityNotes")} /></label><label className="font-bold"><input type="checkbox" className="mr-2" {...form.register("isActive")} />Activo</label><Button className="md:col-span-2" variant="hero" disabled={mutation.isPending}>{mutation.isPending ? "Guardando…" : "Guardar servicio"}</Button></form></Page>; }
export function ProfilePage() { const { profile, refreshProfile } = useAuth(); const handleError = useApiError(); const form = useForm<ProfileValues>({ resolver: zodResolver(profileSchema), values: { fullName: profile?.fullName ?? "", phone: profile?.phone ?? "", city: profile?.city ?? "" } }); const mutation = useMutation({ mutationFn: (values: ProfileValues) => authApi.updateMe({ fullName: values.fullName, phone: values.phone || null, city: values.city || null }), onSuccess: async () => { await refreshProfile(); toast.success("Perfil actualizado"); }, onError: handleError }); return <Page title="Perfil"><section className="rounded-card border bg-card p-6 shadow-soft"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary-soft text-2xl">👤</div><div><h2 className="text-xl font-black">{profile?.fullName ?? "Usuario PetLink"}</h2><p className="text-muted-foreground">{profile?.role === "PROVIDER" ? "Proveedor" : "Dueño"}</p></div></div><form className="mt-6 grid gap-4 md:grid-cols-2" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><Input label="Nombre" error={form.formState.errors.fullName?.message} props={form.register("fullName")} /><Input label="Teléfono" error={form.formState.errors.phone?.message} props={form.register("phone")} /><Input label="Ciudad" error={form.formState.errors.city?.message} props={form.register("city")} /><Button className="md:col-span-2" variant="hero" disabled={mutation.isPending}>{mutation.isPending ? "Guardando…" : "Guardar perfil"}</Button></form></section></Page>; }
export function NotificationsPage() { return <Page title="Notificaciones"><EmptyState title="Todo tranquilo" description="El backend actual permite crear notificaciones; no incluye endpoint de listado para mostrarlas aquí." /></Page>; }
export function BookingDetailPage() { const { id } = useParams(); const { data, isLoading, error } = useQuery({ queryKey: ["bookings", id], queryFn: () => marketplaceApi.bookings.get(id ?? ""), enabled: Boolean(id) }); return <Page title="Detalle de reserva">{isLoading ? <SkeletonGrid /> : error || !data ? <EmptyState title="Reserva no encontrada" description={error instanceof Error ? error.message : "No pudimos cargar el detalle."} /> : <BookingCard booking={data} />}</Page>; }
export function RoleRedirect({ provider }: { provider: boolean }) { const { role } = useAuth(); if ((provider && role !== "PROVIDER") || (!provider && role !== "OWNER")) return <Navigate to="/dashboard" replace />; return null; }

function Page({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-primary">PetLink</p><h1 className="text-3xl font-black md:text-4xl">{title}</h1></div>{action}</div>{children}</section>; }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className="rounded-card border bg-card p-6 shadow-soft"><div className="text-primary">{icon}</div><strong className="mt-4 block text-3xl font-black">{value}</strong><span className="text-sm font-bold text-muted-foreground">{label}</span></article>; }
function Input({ label, error, props, type = "text" }: { label: string; error?: string; props: UseFormRegisterReturn; type?: string }) { return <label className="block text-sm font-bold">{label}<input type={type} className="input-shell mt-2" {...props} />{error && <span className="mt-1 block text-xs text-destructive">{error}</span>}</label>; }
